# Permalinks
permalink:           pretty

# Setup
title:               Jackierinie Huluberg
tagline:             A More than Moderately Okay Data Science Blog
url:                 http://jackiehu0814.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jackie Hu
  url:               https://www.linkedin.com/in/yihuan-jackie-hu/
  email:             

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jackiehu0814

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
